// protoc-gen-easyrpc-rust: read CodeGeneratorRequest and emit a `*_easyrpc.rs`
// with a METHOD_SPECS table. Message types come from prost.
use prost::Message;
use prost_types::compiler::{CodeGeneratorRequest, CodeGeneratorResponse, code_generator_response};

use std::io::{Read, Write};

fn main() {
    let mut input = Vec::new();
    std::io::stdin().read_to_end(&mut input).unwrap();
    let req = CodeGeneratorRequest::decode(&input[..]).expect("decode request");

    let mut files = Vec::new();
    for f in &req.proto_file {
        if !req.file_to_generate.contains(&f.name.clone().unwrap_or_default()) {
            continue;
        }
        let methods = collect_methods(f);
        if methods.is_empty() {
            continue;
        }
        let base = f.name.as_ref().map(|s| s.as_str()).unwrap_or("").trim_end_matches(".proto");
        let content = render(&methods);
        files.push(code_generator_response::File {
            name: Some(format!("{base}_easyrpc.rs")),
            content: Some(content),
            ..Default::default()
        });
    }

    let resp = CodeGeneratorResponse { file: files, ..Default::default() };
    std::io::stdout().write_all(&resp.encode_to_vec()).unwrap();
}

struct M {
    service: String,
    name: String,
    path: String,
    http_method: String,
    client_stream: bool,
    server_stream: bool,
}

fn last_type(t: &str) -> String { t.rsplit('.').next().unwrap_or(t).to_string() }

fn collect_methods(f: &prost_types::FileDescriptorProto) -> Vec<M> {
    let pkg = f.package.clone().unwrap_or_default();
    let mut out = Vec::new();
    for svc in &f.service {
        let svc_name = svc.name.clone().unwrap_or_default();
        for m in &svc.method {
            let name = m.name.clone().unwrap_or_default();
            let path = format!("/{pkg}.{svc_name}/{name}");
            out.push(M {
                service: format!("{pkg}.{svc_name}"),
                name,
                path,
                http_method: "POST".to_string(),
                client_stream: m.client_streaming.unwrap_or(false),
                server_stream: m.server_streaming.unwrap_or(false),
            });
        }
    }
    out
}

fn render(methods: &[M]) -> String {
    let mut s = String::new();
    s.push_str("// Code generated by protoc-gen-easyrpc-rust. DO NOT EDIT.\n");
    s.push_str("pub fn method_specs() -> Vec<crate::protocol::MethodSpec> {\n  vec![\n");
    for m in methods {
        s.push_str(&format!(
            "  crate::protocol::MethodSpec {{ service: {:?}.to_string(), name: {:?}.to_string(), path: {:?}.to_string(), http_method: {:?}.to_string(), client_stream: {}, server_stream: {}, body: String::new() }},\n",
            m.service, m.name, m.path, m.http_method, m.client_stream, m.server_stream
        ));
    }
    s.push_str("  ]\n}\n");
    s
}
